runtime: python
env: flex
entrypoint: gunicorn -b :$PORT ingestapp:app
service: flights

#[START env]
env_variables:
    CLOUD_STORAGE_BUCKET: cloud-training-demos-ml
#[END env]

handlers:
- url: /ingest
  script: ingestapp.app
  login: admin

- url: /.*
  script: ingestapp.app
